Repository QutEcoacoustics/workbench-client, pull requests merged in 2022-08, with the labels that each got.

#1981 Bootstrap fix and global functions
  image.png
  scripts/ssr-tests.ps1
  src/app/app.component.ts
  src/app/components/admin/settings/settings.component.ts
  src/app/components/projects/pages/details/details.component.spec.ts
  src/app/components/projects/pages/details/details.component.ts
  src/app/components/regions/pages/details/details.component.ts
  src/app/services/baw-api/baw-api.service.spec.ts
  src/app/services/baw-api/baw-api.service.ts
  src/app/services/cache/cache-logging.service.ts
  src/app/services/cache/cache-settings.ts
  src/app/services/cache/cache.module.ts
  src/app/services/globals/globals.service.spec.ts
  src/app/services/globals/globals.service.ts
  src/app/styles/bootstrap/components/_index.scss
  src/app/styles/bootstrap/components/_nav.scss
Labels: enhancement, architecture

#1983 Permissions page
  src/app/app.menus.spec.ts
  src/app/components/profile/pages/projects/my-projects.component.spec.ts
  src/app/components/profile/pages/projects/their-projects.component.spec.ts
  src/app/components/profile/pages/sites/my-sites.component.spec.ts
  src/app/components/profile/pages/sites/their-sites.component.spec.ts
  src/app/components/projects/pages/permissions/permissions.component.html
  src/app/components/projects/pages/permissions/permissions.component.spec.ts
  src/app/components/projects/pages/permissions/permissions.component.ts
  src/app/components/projects/projects.menus.ts
  src/app/components/projects/projects.routes.ts
  src/app/components/shared/debounce-input/debounce-input.component.spec.ts
  src/app/components/shared/debounce-input/debounce-input.component.ts
  src/app/components/shared/items/selectable-items/selectable-items.component.html
  src/app/components/shared/items/selectable-items/selectable-items.component.ts
  src/app/components/shared/menu/widgets/allows-original-download/allows-original-download.component.spec.ts
  src/app/components/shared/menu/widgets/permissions-shield/permissions-shield.component.spec.ts
  src/app/components/shared/menu/widgets/permissions-shield/permissions-shield.component.ts
  src/app/components/shared/model-selector/model-selector.component.ts
  src/app/components/shared/shared.components.ts
  src/app/directives/datatable/defaults.directive.ts
  src/app/interfaces/apiInterfaces.spec.ts
  src/app/interfaces/apiInterfaces.ts
  src/app/models/Permission.ts
  src/app/models/Project.ts
  src/app/models/Site.ts
  src/app/pipes/is-unresolved/is-unresolved.pipe.spec.ts
  src/app/pipes/is-unresolved/is-unresolved.pipe.ts
  src/app/services/baw-api/ServiceProviders.ts
  src/app/services/baw-api/ServiceTokens.ts
  src/app/services/baw-api/baw-api.service.ts
  src/app/services/baw-api/permissions/permissions.service.spec.ts
  src/app/services/baw-api/permissions/permissions.service.ts
  src/app/services/baw-api/site/sites.service.ts
  src/app/test/fakes/Permission.ts
  src/app/test/fakes/Project.ts
  src/app/test/helpers/faker.ts
Labels: enhancement, ui feature

#1982 Upload instructions for mac and Rclone
  .gitignore
  src/app/app.server.module.ts
  src/app/components/harvest/components/modal/confirmation.component.ts
  src/app/components/harvest/screens/uploading/batch-uploading.component.html
  src/app/components/harvest/screens/uploading/batch-uploading.component.scss
  src/app/components/harvest/screens/uploading/batch-uploading.component.spec.ts
  src/app/components/harvest/screens/uploading/batch-uploading.component.ts
  src/app/models/Harvest.ts
  src/app/services/universal-device-detector/universal-device-detector.service.ts
  src/app/test/fakes/Harvest.ts
  workbench-client.code-workspace
Labels: enhancement
